spring:
  application:
    name: hazard
  jackson:
    serialization:
      indent-output: true
  sql:
    init:
      mode: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;NON_KEYWORDS=YEAR;INIT=CREATE SCHEMA IF NOT EXISTS MS\;SET SCHEMA MS
    url: jdbc:h2:mem:db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.default_schema: ms
      hibernate.hbm2ddl.auto: none
    defer-datasource-initialization: true

#logging
logging:
  level:
    com.zaxxer.hikari.HikariConfig: info
    org.hibernate: info
    #org.hibernate.SQL: info
    gov.epa.ccte.api.*: debug
    org.springframework: warn