spring:
  application:
    name: chemical
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ccte-pgsql-prod.epa.gov:9999/prod_scdcd_api
    username: app_serv_api
    password: y*#7+rR\P~s(P2]\
    hikari:
      poolName: Hikari
      auto-commit: false
      #data-source-class-name: org.postgresql.ds.PGSimpleDataSource
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.default_schema: ms

# Logging
logging:
  level:
    com.zaxxer.hikari.HikariConfig: info
    org.hibernate.SQL: info
    gov.epa.ccte.api.*: debug
    org.springframework: warn
