spring:
  application:
    name: chemical
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # cloud.gov insert DATABASE_URL
    # url: jdbc:${DATABASE_URL}
    hikari:
      poolName: Hikari
      auto-commit: false
      #data-source-class-name: org.postgresql.ds.PGSimpleDataSource
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.default_schema: ms
      hibernate.hbm2ddl.auto: none
springdoc:
  show-actuator: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
# Logging
logging:
  level:
    com.zaxxer.hikari.HikariConfig: info
    org.hibernate.SQL: info
    gov.epa.ccte.api.*: debug
    org.springframework: warn
