create table chemical_details
(
    id                      integer primary key,
    h_chem_hash_key         varchar(64),
    casrn                   varchar(255),
    compound_id             integer,
    generic_substance_id    integer,
    preferred_name          varchar(255),
    active_assays           integer,
    cpdata_count            bigint,
    mol_formula             varchar(255),
    monoisotopic_mass       double precision,
    percent_assays          double precision,
    pubchem_count           integer,
    pubmed_count            double precision,
    sources_count           bigint,
    qc_level                integer,
    qc_level_desc           varchar(255),
    stereo                  varchar(1),
    isotope                 integer,
    multicomponent          integer,
    total_assays            integer,
    pubchem_cid             integer,
    mol_file                text,
    mrv_file                text,
    related_substance_count bigint,
    related_structure_count bigint,
    mol_image               bytea,
    has_structure_image     integer,
    iupac_name              varchar(5000),
    smiles                  text,
    inchi_string            text,
    average_mass            double precision,
    inchikey                varchar(255),
    qc_notes                varchar(4000),
    qsar_ready_smiles       text,
    ms_ready_smiles         text,
    iris_link               varchar(255),
    pprtv_link              varchar(255),
    wikipedia_article       varchar(255),
    descriptor_string_tsv   varchar(20000),
    is_markush              integer,
    dtxsid                  varchar(100),
    dtxcid                  varchar(100),
    toxcast_select          varchar(10)
);