CREATE SCHEMA IF NOT EXISTS ms;
SET SCHEMA ms;

create table if not exists ms.chemical_details
(
    h_chem_hash_key                    varchar(64),
    dtxsid                             varchar,
    dtxcid                             varchar,
    casrn                              varchar(255),
    compound_id                        integer,
    generic_substance_id               integer,
    preferred_name                     varchar(255),
    active_assays                      integer,
    cpdata_count                       bigint,
    mol_formula                        varchar(255),
    monoisotopic_mass                  double precision,
    percent_assays                     numeric,
    pubchem_count                      integer,
    pubmed_count                       double precision,
    sources_count                      bigint,
    qc_level                           integer,
    qc_level_desc                      varchar(255),
    stereo                             char,
    isotope                            integer,
    multicomponent                     integer,
    total_assays                       integer,
    toxcast_select                     text,
    pubchem_cid                        integer,
    mol_file                           text,
    mrv_file                           text,
    related_substance_count            bigint,
    related_structure_count            bigint,
    mol_image                          bytea,
    has_structure_image                integer,
    iupac_name                         varchar(5000),
    smiles                             text,
    inchi_string                       text,
    average_mass                       double precision,
    inchikey                           varchar(255),
    qc_notes                           varchar(4000),
    qsar_ready_smiles                  text,
    ms_ready_smiles                    text,
    iris_link                          varchar(255),
    pprtv_link                         varchar(255),
    wikipedia_article                  varchar(255),
    expocat_median_prediction          varchar(50),
    expocat                            varchar(5),
    nhanes                             varchar(5),
    toxval_data                        varchar(5),
    water_solubility_test              double precision,
    water_solubility_opera             double precision,
    viscosity_cp_cp_test_pred          double precision,
    vapor_pressure_mmhg_test_pred      double precision,
    vapor_pressure_mmhg_opera_pred     double precision,
    thermal_conductivity               double precision,
    tetrahymena_pyriformis             double precision,
    surface_tension                    double precision,
    soil_adsorption_coefficient        double precision,
    oral_rat_ld50_mol                  double precision,
    opera_km_days_opera_pred           double precision,
    octanol_water_partition            double precision,
    octanol_air_partition_coeff        double precision,
    melting_point_degc_test_pred       double precision,
    melting_point_degc_opera_pred      double precision,
    hr_fathead_minnow                  double precision,
    hr_diphnia_lc50                    double precision,
    henrys_law_atm                     double precision,
    flash_point_degc_test_pred         double precision,
    devtox_test_pred                   double precision,
    density                            double precision,
    boiling_point_degc_test_pred       double precision,
    boiling_point_degc_opera_pred      double precision,
    biodegradation_half_life_days      double precision,
    bioconcentration_factor_test_pred  double precision,
    bioconcentration_factor_opera_pred double precision,
    atmospheric_hydroxylation_rate     double precision,
    ames_mutagenicity_test_pred        double precision,
    pkaa_opera_pred                    double precision,
    pkab_opera_pred                    double precision,
    descriptor_string_tsv              varchar(20000),
    is_markush                         integer
);

create table ms.chemical_search
(
    id                  integer  not null,
    dtxsid              varchar(20),
    dtxcid              varchar(20),
    casrn               varchar(255),
    smiles              text,
    preferred_name      varchar(255),
    search_group        varchar(50),
    search_name         varchar(50),
    search_value        text,
    modified_value      text,
    rank                integer,
    has_structure_image integer,
    is_markush          integer,
    created_by          varchar(50),
    created_at          timestamp  default now()
);

create table ms.chemical_properties
(
    id          integer    not null,
    dtxsid      varchar(45),
    dtxcid      varchar(45),
    prop_type   text,
    unit        varchar(255),
    name        varchar(255),
    prop_value  double precision,
    source      varchar(255),
    description varchar(1024),
    created_by  varchar(50),
    created_at  timestamp   default now(),
    property_id varchar(300)
);

create table ms.fate
(
    id            integer not null,
    dtxsid        varchar(45),
    dtxcid        varchar(45),
    endpoint_name varchar(255),
    result_value  double precision,
    unit          varchar(255),
    max_value     double precision,
    min_value     double precision,
    model_source  varchar(255),
    description   varchar(1024),
    value_type    text,
    created_by    varchar(50),
    created_at    timestamp   default now()
);

create table ms.chemical_lists
(
    id                 integer  not null,
    list_name          varchar(255),
    visibility         varchar(255),
    is_visible         boolean,
    short_description  text,
    long_description   text,
    created_date       timestamp,
    last_modified_date timestamp,
    created_by         varchar(255),
    chemical_count     integer,
    created_at         timestamp default now(),
    label              varchar(255),
    type               varchar(100)
);

create table ms.chemical_list_details
(
    id                      integer not null,
    dtxsid                  varchar(50),
    casrn                   varchar(255),
    compound_id             integer,
    generic_substance_id    integer,
    preferred_name          text,
    active_assays           integer,
    cpdata_count            integer,
    mol_formula             varchar(255),
    mol_weight              numeric,
    monoisotopicmass        numeric,
    percent_assays          integer,
    pubchem_count           integer,
    pubmed_count            numeric,
    qc_level                integer,
    qc_level_desc           varchar(255),
    stereo                  varchar(1),
    total_assays            integer,
    toxcast_select          text,
    pubchem_cid             integer,
    list_name               text,
    list_label              text,
    list_category           text,
    list_shortdesc          text,
    list_is_visible         boolean,
    list_visibility         text,
    sources_count           integer,
    multi_component         integer,
    isotope                 integer,
    has_structure_image     boolean,
    related_substance_count integer,
    related_structure_count integer,
    inchi                   text,
    inchi_key               text,
    iupac_name              text,
    smiles                  text,
    created_at              timestamp   default now(),
    created_by              varchar(50)
);

create table ms.chemical_synonym
(
    dtxsid             varchar(45),
    pc_code            text,
    valid_synonym      text,
    good_synonyms      text,
    delete_synonyms    text,
    other_synonyms     text,
    beilstein_synonyms text,
    alternate_synonyms text
);
