name: Application-security-scan

on:
  push:
   branches: [ dev, staging, dev-756 ]
    
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
     - name: perform passive scan
       uses: zaproxy/action-api-scan@v0.6.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         format: openapi
         target: 'https://api-ccte-stg.epa.gov/docs/chemical.json'
        #specify the scanning mode as 'Attack' for active scan on the target API
         #cmd_options: '-a'
         
