name: Application-security-scan

on:
  push:
   branches: [ dev, staging ]
    
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
     - name: perform passive scan
       uses: zaproxy/action-api-scan@v0.6.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         format: openapi
         target: 'https://api-ccte-stg.epa.gov/docs/chemical.json'
         cmd_options: '-a'
         #active_scan: false
         
